export interface DiagnosticsState {
  roomId: string;
  localUserId: string;
  remoteUserId: string | null;
  role: 'host' | 'participant' | 'none';
  wsConnected: boolean;
  serverRoomId: string | null;
  wsRoomId: string | null;
  urlRoomId: string | null;
  storedRoomId: string | null;
  connectionState: RTCPeerConnectionState | 'uninitialized';
  iceConnectionState: RTCIceConnectionState | 'uninitialized';
  signalingState: RTCSignalingState | 'uninitialized';
  iceGatheringState: RTCIceGathererState | 'uninitialized';
  localVideoTrack: boolean;
  localAudioTrack: boolean;
  localVideoEnabled: boolean;
  localAudioEnabled: boolean;
  localStreamId: string | null;
  localTrackIds: string[];
  remoteVideoTrack: boolean;
  remoteAudioTrack: boolean;
  remoteStreamId: string | null;
  remoteTrackIds: string[];
  remoteVideoReadyState: number;
  remoteVideoPaused: boolean;
  remoteVideoMuted: boolean;
  remoteVideoCurrentTime: number;
  remoteVideoWidth: number;
  remoteVideoHeight: number;
  remoteAutoplayBlocked: boolean;
  recentLogs: Array<{ time: string; text: string; level: 'info' | 'warn' | 'error' | 'success' }>;
  renderCount?: number;
  wsTxCount?: number;
  wsRxCount?: number;
  peerConnectionCount?: number;
  localTrackCount?: number;
  remoteTrackCount?: number;
  isScreenSharing?: boolean;
  screenShareOwner?: 'local' | 'remote' | null;
}
